### ISSUE TITLE
Education section missing?

### ISSUE THREAD

**Issue by marcusisinger** [jcoelho93/personal-website#13]
Great project!

However, it seems an education section should be added, since you have the information in resume.json?

**Comment by jcoelho93** [comment]
Thanks! 
There’s a small how-to in the README.
But I’m accepting PRs of you’re interested in collaborating.

**Comment by gluehbirnenkopf** [comment]
@gIcyyy I also forked the work from @jcoelho93 and added within other sections, the education section. You can take a look at my site as well:
https://github.com/gluehbirnenkopf/javascript-cv

leon-gregori.com
